owner: chaotic-aur
repo: chaotic-uptimes
assignees: dr460nf1r3

sites:
  - name: Homepage
    url: https://aur.chaotic.cx
  - name: The router
    url: https://geo-mirror.chaotic.cx
  - name: de | dr460nf1r3
    urL: https://de-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate

status-website:
  baseUrl: /chaotic-uptimes
  cname: uptimes.chaotic.cx
  logoUrl: https://avatars.githubusercontent.com/u/66071775?s=400&u=99bc0536e7e77fe3e58839996600848f2d930ed5&v=4
  name: Chaotic-AUR Uptimes
  introTitle: Want to know which mirrors are up?
  introMessage: This is the status page of Chaotic-AUR which shows current uptime status and historic data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://aur.chaotic.cx

#commitMessages:
#  commitAuthorName: "Chaotic-AUR Uptime Bot"
#  commitAuthorEmail: "upptime@chaotic.cx"

#user-agent: chaotic-aur
