owner: chaotic-aur
repo: chaotic-uptimes
assignees: dr460nf1r3

sites:
  - name: Homepage
    url: https://aur.chaotic.cx
  - name: The router
    url: https://geo-mirror.chaotic.cx
  - name: br | UFSCar Alcateia
    url: https://br-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - thotypous
  - name: cdn | Fosshost
    url: https://cdn-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - dr460nf1r3
  - name: de | dr460nf1r3
    urL: https://de-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - dr460nf1r3
  - name: es-2 | Ícar
    urL: https://es-2-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - juxuanu
  - name: sg | Freedif
    url: https://sg-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - dr460nf1r3
  - name: us-fl | Alisson
    url: https://us-fl-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - alissonlauffer
  - name: us-mi | Technetium1
    url: https://us-mi-mirror.chaotic.cx/no-failover/chaotic-aur/lastupdate
    assignees:
      - Technetium1

status-website:
  baseUrl: /chaotic-uptimes
  cname: uptimes.chaotic.cx
  logoUrl: https://avatars.githubusercontent.com/u/66071775?s=400&u=99bc0536e7e77fe3e58839996600848f2d930ed5&v=4
  name: Chaotic-AUR Uptimes
  introTitle: Want to know which mirrors are up?
  introMessage: This is the status page of Chaotic-AUR which shows current uptime status and historic data.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Homepage
      href: https://aur.chaotic.cx

commitMessages:
  commitAuthorName: "Chaotic-AUR Uptime Bot"
  commitAuthorEmail: "upptime@chaotic.cx"

user-agent: chaotic-aur
